/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellScreen`; params?: Router.UnknownInputParams; } | { pathname: `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/homepage_style`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/itemdetail`; params?: Router.UnknownInputParams; } | { pathname: `/itemdetailcss`; params?: Router.UnknownInputParams; } | { pathname: `/personal`; params?: Router.UnknownInputParams; } | { pathname: `/personalcss`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/registration_style`; params?: Router.UnknownInputParams; } | { pathname: `/sellscreen_style`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SellScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage_style`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/itemdetail`; params?: Router.UnknownOutputParams; } | { pathname: `/itemdetailcss`; params?: Router.UnknownOutputParams; } | { pathname: `/personal`; params?: Router.UnknownOutputParams; } | { pathname: `/personalcss`; params?: Router.UnknownOutputParams; } | { pathname: `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/registration_style`; params?: Router.UnknownOutputParams; } | { pathname: `/sellscreen_style`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/SellScreen${`?${string}` | `#${string}` | ''}` | `/homepage${`?${string}` | `#${string}` | ''}` | `/homepage_style${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/itemdetail${`?${string}` | `#${string}` | ''}` | `/itemdetailcss${`?${string}` | `#${string}` | ''}` | `/personal${`?${string}` | `#${string}` | ''}` | `/personalcss${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `/registration_style${`?${string}` | `#${string}` | ''}` | `/sellscreen_style${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellScreen`; params?: Router.UnknownInputParams; } | { pathname: `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/homepage_style`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/itemdetail`; params?: Router.UnknownInputParams; } | { pathname: `/itemdetailcss`; params?: Router.UnknownInputParams; } | { pathname: `/personal`; params?: Router.UnknownInputParams; } | { pathname: `/personalcss`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/registration_style`; params?: Router.UnknownInputParams; } | { pathname: `/sellscreen_style`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
